# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-17 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='文章内容')),
            ],
        ),
        migrations.AlterField(
            model_name='picture',
            name='img',
            field=models.ImageField(upload_to='ge/ge', verbose_name='图片'),
        ),
    ]
