# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-17 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0002_auto_20190817_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pic.Topic'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='img',
            field=models.ImageField(upload_to='user_directory_path', verbose_name='图片'),
        ),
    ]
