# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-17 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pic.models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0003_auto_20190817_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='用户名')),
            ],
        ),
        migrations.AlterField(
            model_name='picture',
            name='img',
            field=models.ImageField(upload_to=pic.models.user_directory_path, verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='topic',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pic.User'),
        ),
    ]
