# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-19 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('pwd', user.models.CCharFiled(max_length=20)),
            ],
        ),
    ]
